apiVersion: v1
kind: ServiceAccount
metadata:
  name: jgroups-kubeping-service-account
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jgroups-kubeping-cluster-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - "get"
      - "list"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jgroups-kubeping-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: jgroups-kubeping-cluster-role
subjects:
  - kind: ServiceAccount
    name: jgroups-kubeping-service-account
