name: CI
on:
  push:
    branches: [kustomize]
  pull_request:
    branches: [kustomize]
env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }}
jobs:
  k8s-policy-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install kubectl and kustomize
        uses: azure/setup-kubectl@v1
      - name: Run kustomize
        run: kubectl kustomize testwar/base/ > out.yaml
      - name: Install Datree
        run: curl https://get.datree.io | /bin/bash
      - uses: actions/upload-artifact@v2
        with:
          name: kubernetes.yaml
          path: out.yaml
      - name: Run Datree's policy check
        run: datree test out.yaml > datree.log | exit 0
      - uses: actions/upload-artifact@v2
        with:
          name: datree.log
          path: datree.log
      - name: Run Kubeval validation out.yaml
        uses: instrumenta/kubeval-action@master
        with:
          files: out.yaml
      - name: Run Kubeval validation
        uses: instrumenta/kubeval-action@master
        continue-on-error: true
        with:
          files: testwar/.
      - name: Run OPA conftest
        uses: instrumenta/conftest-action@master
        with:
          files: out.yaml
          policy: github.com/instrumenta/policies.git//kubernetes
          
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
